export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY'
export const CLEAR_ORDER = "CLEAR_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_POSTS = "FETCH_POSTS";

